In [1]:
from joblib import dump,load
import numpy as np
import pandas as pd
import pickle
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

housing = pd.read_csv('data.csv')

from sklearn.model_selection import train_test_split
train_set,test_set = train_test_split(housing,test_size=0.2,random_state=42)

# # Stratify Sampling

from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
for train_index,test_index in split.split(housing,housing['CHAS']):
    stratify_train_set = housing.loc[train_index]
    stratify_test_set = housing.loc[test_index]

housing = stratify_train_set.copy()

# # Handling Missing Values
from sklearn.impute import SimpleImputer

housing = stratify_train_set.drop("MEDV",axis=1)
housing_labels = stratify_train_set["MEDV"].copy()


# # Creating Pipeline

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy='median')),
    ('std_scaler',StandardScaler()),
])
housing_num_tr = my_pipeline.fit_transform(housing)

In [2]:
model = load('Jaunpur.joblib')
arr = np.array([[0.03578,20,3.33,0,0.4429,7.82,64.5,4.6947,5,216,14.9,387.31,3.76]])
arr

array([[3.5780e-02, 2.0000e+01, 3.3300e+00, 0.0000e+00, 4.4290e-01,
        7.8200e+00, 6.4500e+01, 4.6947e+00, 5.0000e+00, 2.1600e+02,
        1.4900e+01, 3.8731e+02, 3.7600e+00]])

In [3]:
prepared_data = my_pipeline.transform(arr)
prepared_data

C:\Users\amarn\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([[-0.44095418,  0.41419706, -1.16677847, -0.27288841, -0.98657928,
         2.16743091, -0.160855  ,  0.4524252 , -0.5429938 , -1.16548275,
        -1.68026757,  0.35348708, -1.24974192]])

In [4]:
model.predict(prepared_data)

array([46.287])